// Generate the sitemap and robots from what is ACTUALLY on disk.
//
// The sitemap was a hand-written string in the worker. By the time anyone
// looked it was missing /parent, /clinician and every page added since — the
// exact silent drift that the voice manifest had, with the same cause (a list
// maintained by hand next to a thing that changes) and the same fix.
//
// It also listed nothing that should be hidden, which is luck rather than
// design. Private surfaces are now excluded by an explicit rule, so adding a
// new private page cannot accidentally publish it.
//
//   node tools/seo/build-sitemap.mjs

import { writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ORIGIN = 'https://kide.us';
const ROOT = 'public';

/* Never index. Each of these has a reason, not a preference:
 *  - /parent, /clinician  a child's practice record. Indexing it would be a
 *                         privacy failure even though the data is local-only.
 *  - /bench, /engine      developer instrumentation. Ranking for it would
 *                         waste crawl budget and confuse a parent who lands on it.
 *  - /scene               an internal rig, not a page.
 */
const PRIVATE = [/^\/parent/, /^\/clinician/, /^\/bench/, /^\/engine/, /^\/scene/];

/* Priority reflects what we would most like a stranger to land on.
 * /sounds outranks the product pages deliberately: it is the surface that
 * answers a question someone is actively searching for, and the product is
 * what they find once they trust the answer. */
const PRIORITY = [
  [/^\/$/,          '1.0', 'weekly'],
  [/^\/sounds$/,    '0.9', 'weekly'],
  [/^\/sounds\//,   '0.8', 'monthly'],
  [/^\/words$/,     '0.9', 'weekly'],
  [/^\/play$/,      '0.8', 'weekly'],
  [/^\/guides$/,    '0.8', 'monthly'],
  [/^\/guides\//,   '0.7', 'monthly'],
  // The only page aimed at the customer who pays. Low volume, high intent --
  // one clinician is worth more here than a hundred parents, and there are far
  // fewer of them searching.
  [/^\/for-slps$/,  '0.9', 'monthly'],
  [/^\/(privacy|terms)$/, '0.3', 'yearly'],
];

function routes(dir = ROOT, prefix = '') {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (!statSync(p).isDirectory()) {
      if (entry === 'index.html' && prefix) out.push(prefix);
      continue;
    }
    out.push(...routes(p, `${prefix}/${entry}`));
  }
  return out;
}

const all = ['/', ...routes()].filter((r, i, a) => a.indexOf(r) === i).sort();
const pub = all.filter((r) => !PRIVATE.some((rx) => rx.test(r)));
const excluded = all.filter((r) => PRIVATE.some((rx) => rx.test(r)));

const meta = (r) => PRIORITY.find(([rx]) => rx.test(r)) || [null, '0.5', 'monthly'];

const xml = '<?xml version="1.0" encoding="UTF-8"?>'
  + '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
  + pub.map((r) => {
      const [, priority, changefreq] = meta(r);
      return `<url><loc>${ORIGIN}${r === '/' ? '/' : r}</loc>`
        + `<changefreq>${changefreq}</changefreq><priority>${priority}</priority></url>`;
    }).join('')
  + '</urlset>';

// robots.txt: the private surfaces are disallowed explicitly as well as being
// absent from the sitemap. Absence is not an instruction; Disallow is.
const robots = [
  'User-agent: *',
  'Allow: /',
  ...excluded.map((r) => `Disallow: ${r}/`),
  '',
  `Sitemap: ${ORIGIN}/sitemap.xml`,
  '',
].join('\n');

writeFileSync('src/worker/seo-generated.ts',
  '// GENERATED by tools/seo/build-sitemap.mjs -- do not hand-edit.\n'
  + '// The previous hand-written sitemap silently went stale and was missing five\n'
  + '// live pages. This one is derived from the pages that actually exist.\n\n'
  + `export const SITEMAP = ${JSON.stringify(xml)};\n\n`
  + `export const ROBOTS = ${JSON.stringify(robots)};\n\n`
  + `export const PUBLIC_ROUTES = ${JSON.stringify(pub)};\n`);

writeFileSync(`${ROOT}/robots.txt`, robots);
writeFileSync(`${ROOT}/sitemap.xml`, xml);

console.log(`sitemap: ${pub.length} public routes`);
console.log(`  excluded as private: ${excluded.join(', ') || 'none'}`);
if (existsSync(`${ROOT}/ads.txt`)) console.log('  WARNING: public/ads.txt still present');
